### ISSUE TITLE
assign static ip per client

### ISSUE THREAD

**Issue by Etudianttestnan** [IBCNServices/easy-openvpn-server#12] opened 2022-01-06 12:54 UTC
Hello

how can i assign static ip per client, 
example : 10.108.7.X

thank you

**Comment by galgalesh** [comment] 2022-01-06 13:37
Duplicate of https://github.com/IBCNServices/easy-openvpn-server/issues/5

This is currently not supported. I don't plan on implementing this myself, but contributions are always welcome.

**Closed by galgalesh** 2022-01-06 13:37 UTC
Labels: duplicate
